### ISSUE TITLE
Add a "processing" dialog

### ISSUE THREAD

**Issue by quequotion** [jgreco/mpv-txt#1]
I usually open files in mpv by right-clicking them in a file browser and selecting "open in mpv". Between selecting a file and the mpv-txt stream opening, nothing appears to be happening on the desktop (unless one is watching a cpu or process monitor). It would be great to have some kind of "in progress" dialog here.

How feasible does rendering a progress bar in mpv sound?

**Comment by jgreco** [comment]
I've been thinking about this too.  I'm  not sure there's a straightforward way to display progress in mpv since that would require sending progress data back from the python process that's subprocess'd out from mpv.  That should be possible, but it would be pretty hacky.  It would probably involve text2media.py writing the progress out to a file, then a separate lua userscript reading that file to render the progress bar in mpv.  Then there is the problem of mpv not actually creating a window in which to render anything until the txt_hook finishes.  I'm not sure how to work around that.

A more straightforward approach would be to display a progress bar with python in a separate window (using TKinter to avoid pulling in another dependency.)  I think I should be able to do this without much difficulty, and make it optional.

**Comment by jgreco** [comment]
I've implemented the TKinter GUI progress bar idea in commit 363a0e7fa4fa07bbb0daaa4180a7152fac627f32

I may revisit the idea of a progress bar displayed in mpv in the future.

**Comment by quequotion** [comment]
Awesome! Thanks for taking it on.

It's a long shot with my limited skills, but I'll see if I can't find some sort of approach for an embedded progress bar myself. I may be back with a pull request some day!
